title: Your awesome title
author: Asalim9
email: asalim9@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  My description is: Hi

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
